
import { Project, ProjectStatus, TimelineEntry } from './types';

export const MONTHS = [
  { name: 'Januar', weeks: [1, 2, 3, 4] },
  { name: 'Februar', weeks: [5, 6, 7, 8] },
  { name: 'März', weeks: [9, 10, 11, 12, 13] },
  { name: 'April', weeks: [14, 15, 16, 17] },
  { name: 'Mai', weeks: [18, 19, 20, 21, 22] },
  { name: 'Juni', weeks: [23, 24, 25, 26] },
  { name: 'Juli', weeks: [27, 28, 29, 30, 31] },
  { name: 'August', weeks: [32, 33, 34, 35] },
  { name: 'September', weeks: [36, 37, 38, 39, 40] },
  { name: 'Oktober', weeks: [41, 42, 43, 44] },
  { name: 'November', weeks: [45, 46, 47, 48] },
  { name: 'Dezember', weeks: [49, 50, 51, 52] },
];

export const MOCK_PROJECTS: Project[] = [
  {
    id: '1',
    kzl_ktr: 'XXX',
    status: ProjectStatus.ANGEBOT,
    statusInfo: 'Hr Göhler',
    ort: 'Hoyerswerda',
    bauvorhaben: 'Ferienwohnungen am Fließ',
    l_gewerk: 'HLS',
    auftraggeber: 'Terpe Bau',
    abgabe: '27.01.26',
    agnr_pnr: '',
    summe: 274167,
    pl: '',
    bl_ma: '',
    // Fix: Explicitly cast type to narrow from string to union literal
    timeline: Array.from({ length: 11 }, (_, i) => ({ week: 9 + i, code: i === 0 ? '26' : 'x', type: 'planning' as const })),
  },
  {
    id: '2',
    kzl_ktr: 'HBB',
    status: ProjectStatus.ANGEBOT,
    statusInfo: 'Hr. Ssyckor',
    ort: 'Bautzen',
    bauvorhaben: 'Hentschke Druckluft Halle',
    l_gewerk: 'HLS',
    auftraggeber: 'Hentschke Bau',
    abgabe: '30.01.26',
    agnr_pnr: '',
    summe: 30000,
    pl: 'MG',
    bl_ma: '',
    timeline: [{ week: 5, code: '26', type: 'planning' }, { week: 6, code: 'x', type: 'planning' }],
  },
  {
    id: '3',
    kzl_ktr: 'XXX',
    status: ProjectStatus.AUFTRAG,
    statusInfo: 'In Arbeit',
    ort: 'Berlin',
    bauvorhaben: 'Wohngebäude Julia',
    l_gewerk: 'HLSP',
    auftraggeber: 'Kleusberg',
    abgabe: '15.12.25',
    agnr_pnr: '',
    summe: 366596,
    pl: '',
    bl_ma: 'ABN',
    // Fix: Explicitly cast type to narrow from string to union literal
    timeline: Array.from({ length: 15 }, (_, i) => ({ week: 20 + i, code: i === 0 ? '26' : (i === 14 ? 'ABN' : 'x'), type: 'execution' as const })),
  },
  {
    id: '4',
    kzl_ktr: 'SZS',
    status: ProjectStatus.AUFTRAG,
    statusInfo: 'Bestätigt',
    ort: 'Dresden',
    bauvorhaben: 'Asternweg Wohnbau',
    l_gewerk: 'HLS',
    auftraggeber: 'Rommel Bau',
    abgabe: '25.09.25',
    agnr_pnr: '',
    summe: 460000,
    pl: 'MG',
    bl_ma: '',
    timeline: [
      { week: 1, code: '26', type: 'execution' },
      { week: 2, code: 'BST', type: 'execution' },
      // Fix: Explicitly cast type to narrow from string to union literal
      ...Array.from({ length: 10 }, (_, i) => ({ week: 3 + i, code: 'x', type: 'execution' as const })),
      { week: 40, code: 'MDL', type: 'info' },
      // Fix: Explicitly cast type to narrow from string to union literal
      ...Array.from({ length: 6 }, (_, i) => ({ week: 41 + i, code: 'x', type: 'execution' as const })),
    ],
  },
  {
    id: '5',
    kzl_ktr: 'GRU',
    status: ProjectStatus.ERLEDIGT,
    statusInfo: 'Abgeschlossen',
    ort: 'Altenpleen',
    bauvorhaben: 'Schulerweiterung',
    l_gewerk: 'HLS',
    auftraggeber: 'Kleusberg',
    abgabe: '25.11.25',
    agnr_pnr: '',
    summe: 172500,
    pl: 'RM',
    bl_ma: '',
    timeline: [
      // Fix: Explicitly cast type to narrow from string to union literal
      ...Array.from({ length: 8 }, (_, i) => ({ week: 5 + i, code: i === 0 ? '25' : 'x', type: 'milestone' as const })),
      { week: 20, code: 'FM', type: 'info' },
      { week: 25, code: 'X', type: 'milestone' },
    ],
  },
];
